[package]
name = "ckb-spawn-current-cycles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = { version="0.14.0", features=["ckb2023"] }
